services:
    metamodels.filter_fromto.factory:
        class: MetaModels\FilterFromToBundle\FilterSetting\FromToFilterSettingTypeFactory
        tags:
          - { name: metamodels.filter_factory }
    metamodels.filter_fromtodate.factory:
        class: MetaModels\FilterFromToBundle\FilterSetting\FromToDateFilterSettingTypeFactory
        tags:
          - { name: metamodels.filter_factory }
    metamodels.filter_fromto.add_custom_regexp_listener:
        class: MetaModels\FilterFromToBundle\EventListener\FilterRangeDateRegexpListener
        tags:
          - { name: 'contao.hook', hook: 'addCustomRegexp', method: 'onAddCustomRegexp' }
